### ISSUE TITLE
jQuery Migrate dependency not installed

### ISSUE THREAD

**Issue by Bkelso** [Spea/SpBowerBundle#100]
Hello,

I added "jquery-migrate": "latest" to my bower file and then used sp:bower:install successfully.

However, symfony throws an exception saying that the jquery_migrate_js asset doesn't exist. I installed several other jquery-related libraries without any issue, and given the lack of error message, it's quite hard for me to figure what caused this.

**Comment by Spea** [comment]
not a problem of this bundle
