### ISSUE TITLE
Way to apply css filter

### ISSUE THREAD

**Issue by chadyred** [Spea/SpBowerBundle#105]
Hello,

I try to config "components-font-awesome":"latest". I have add the plugin in my bower.json, I have update. I try this in configuration : 

<pre>
assetic:
        enabled: true
        nest_dependencies: true
        filters:
            css:
                - ?yui_css
            js:
                - ?uglifyjs
            packages:
                bootstrap:
                    css:
                        - cssembed
                        - cssrewrite 
                flat-ui-official:
                    css:
                        - cssrewrite
</pre>

and I insert the package with the path in sp:bower:loist : 

@components_font_awesome_css

But the filter dont apply to it, their is bad way in the css like ../bundles/me//../fonts/ etc.
...but with : 

<pre>
assetic:
  #...  
  assets:
        bootstrap:
            inputs:
                - "bundles/floriandemo/components/Flat-UI/bootstrap/css/bootstrap.css"
            filters:
                - cssrewrite 
        flat_ui:
            inputs:
                - "bundles/floriandemo/components/Flat-UI/css/flat-ui.css"
            filters:
                - cssrewrite      
        font_awesome:
            inputs:
                - "bundles/floriandemo/components/components-font-awesome/css/font-awesome.min.css"
            filters:
                - cssrewrite 
</pre>
There is no problem, but....

1) why the package filter don't apply to the bower package...

And why when i have had this plugin : 

        "flat-ui-official":"latest"

I don't have any alias path to the css file, which are : 

<pre>
 - "bundles/floriandemo/components/Flat-UI/css/flat-ui.css"
- "bundles/floriandemo/components/Flat-UI/bootstrap/css/bootstrap.css"
</pre>

2) There's a way to have it ?

Thanks.

**Comment by Spea** [comment]
is this still an issue? if so, can you add your bower.json?

**Comment by Spea** [comment]
Closing for now until I get more feedback.
