### ISSUE TITLE
Add more commands to the Bundle 

### ISSUE THREAD

**Issue by paquitodev** [Spea/SpBowerBundle#113]
Hi @Spea I'm just wondering if it will be possible to add more [commands][1] for this bundle since right now for example I'm having a upset issue and I can't find what is causing it since the only commands I have through the bundle are: `update`,`install` and `list` (this one never worked for me). Could be possible to add them?

For example I'm running `sp:bower:install` and I'm getting this output:

    bower jquery#>=1.6                        validate 2.1.1 against git://github.com/jquery/jquery.git#>=1.6
    bower jquery-1.11.0#1.11.0                  cached git://github.com/jquery/jquery.git#1.11.0
    bower jquery-1.11.0#1.11.0                validate 1.11.0 against git://github.com/jquery/jquery.git#1.11.0
    bower bootstrap#~3.2.0                      cached git://github.com/twbs/bootstrap.git#3.2.0
    bower bootstrap#~3.2.0                    validate 3.2.0 against git://github.com/twbs/bootstrap.git#~3.2.0
    bower requirejs#~2.1.11                     cached git://github.com/jrburke/requirejs-bower.git#2.1.15
    bower requirejs#~2.1.11                   validate 2.1.15 against git://github.com/jrburke/requirejs-bower.git#~2.1.11
    bower moment#2.7.0                          cached git://github.com/moment/moment.git#2.7.0
    bower moment#2.7.0                        validate 2.7.0 against git://github.com/moment/moment.git#2.7.0
    bower blueimp-load-image#>=1.13.0           cached git://github.com/blueimp/JavaScript-Load-Image.git#1.13.0
    bower blueimp-load-image#>=1.13.0         validate 1.13.0 against git://github.com/blueimp/JavaScript-Load-Image.git#>=1.13.0
    bower blueimp-tmpl#>=2.5.4                  cached git://github.com/blueimp/JavaScript-Templates.git#2.5.4
    bower blueimp-tmpl#>=2.5.4                validate 2.5.4 against git://github.com/blueimp/JavaScript-Templates.git#>=2.5.4
    bower blueimp-canvas-to-blob#>=2.1.1        cached git://github.com/blueimp/JavaScript-Canvas-to-Blob.git#2.1.1
    bower blueimp-canvas-to-blob#>=2.1.1      validate 2.1.1 against git://github.com/blueimp/JavaScript-Canvas-to-Blob.git#>=2.1.1
    bower                                    ECONFLICT Unable to find suitable version for bootstrap

So, something is failing but what? Did you get my point?

 [1]: http://bower.io/docs/api/#commands

**Comment by Spea** [comment]
Should be fixed in the latest master version
