### ISSUE TITLE
Lock file?

### ISSUE THREAD

**Issue by bassrock** [Spea/SpBowerBundle#120]
Currently it seems like sp:bower:update and sp:bower:install perform the same as there is no lock file that I can see in the structure for it to follow. I recommend we introduce lock file support so that this behaves as expected like composer or a regular bower install.

**Comment by Spea** [comment]
Actually both commands just execute `bower update` and `bower install`. When I execute `sp:bower:install` twice, the second one does not do anything at all. I guess it has something to do with your configuration, would be nice if you could provide some information about that.

**Comment by bassrock** [comment]
@Spea does a bower.lock get put anywhere? I have my .gitignore setup to ignore everything in the public/components directory with the bower.json file inside the Resources/config/bower directory.

![screen shot 2015-01-13 at 10 54 35 am](https://cloud.githubusercontent.com/assets/1010384/5726743/9854e3be-9b12-11e4-8cb7-535137c3f5e9.png)

**Comment by Spea** [comment]
Currently there is no such thing as a `bower.lock` file. There are some discussion on the bower project to implement it, but right now there is no such thing. So I'm still not sure what problem you have.

**Comment by Wirone** [comment]
He has a problem with assumption that lock file should exist :-) For Composer users it's obvious, for me **was** too, then I read [this](https://github.com/bower/bower/pull/1592).

If you want to keep version consistency through **do not** use `~` on dependencies, but set exact version.
