### ISSUE TITLE
Asset q_js not found

### ISSUE THREAD

**Issue by martijngastkemper** [Spea/SpBowerBundle#126]
I try to install [q](https://github.com/kriskowal/q):

``` json
// bower.json
{
    "name": "bundle-name",
    "dependencies": {
		"q": "1.0.1"
    }
}
```
q is properly downloaded according the output of app/console sp:bower:install
```
bower q#1.0.1                   cached git://github.com/kriskowal/q.git#1.0.1
bower q#1.0.1                 validate 1.0.1 against git://github.com/kriskowal/q.git#1.0.1
bower q#1.0.1                  install q#1.0.1

q#1.0.1 ../../../../src/MG/RecurringBundle/Resources/public/components/q
```

But I get the error asset q_js not found when I use @q_js in my Twig template. The output of sp:bower:list is empty, so there is a problem with installing that package.

I tried to install jQuery and Bootstrap, no problems with that.

**Comment by Spea** [comment]
The problem here is, that the bower package does not define a `main` section. So this is the same problem as describe in https://github.com/Spea/SpBowerBundle/issues/100#issuecomment-49417695 and thus not a problem of this bundle.
