### ISSUE TITLE
Latest Dev Now Requires Symfony 2.8

### ISSUE THREAD

**Issue by bassrock** [Spea/SpBowerBundle#128]
The version for "0.12.*@dev" now requires Symfony 2.8. Is this intentional or by mistake?

**Comment by hallabro** [comment]
As far as I can see it requires `symfony/framework-bundle 2.8.x-dev` which is a bit strange to me as well.
Note that `symfony/framework-bundle` versioning is not the same as `symfony/symfony`.

Quoting http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/index.html:

     Since SensioFrameworkExtraBundle 3.0 its release cycle is out of sync with Symfony's release cycle.

**Comment by hallabro** [comment]
I have opened a pull request for this issue [here](https://github.com/Spea/SpBowerBundle/pull/129).

**Comment by lavoiesl** [comment]
:+1:

**Comment by Spea** [comment]
Fixed in #129
