### ISSUE TITLE
Composer complaining when using with Symfony 3

### ISSUE THREAD

**Issue by mhall58** [Spea/SpBowerBundle#134]
Problem 1
    - Installation request for sp/bower-bundle ^0.11.0 -> satisfiable by sp/bower-bundle[v0.11].
    - Conclusion: remove symfony/symfony v3.0.2
    - Conclusion: don't install symfony/symfony v3.0.2
    - sp/bower-bundle v0.11 requires symfony/process ~2.1 

..

**Comment by chadyred** [comment]
It's the require that match until the 2.99999999.99999999 not 3
```
        "symfony/framework-bundle": "~2.1",
```

**Comment by eidsonator** [comment]
I've made the changes suggested by @chadyred  in a fork and tested.  It works well.

I've created a [pull request](https://github.com/Spea/SpBowerBundle/pull/136).

**Comment by Spea** [comment]
Solved with #136
