### ISSUE TITLE
Update to Symfony 3.1 Please

### ISSUE THREAD

**Issue by DJWindless** [Spea/SpBowerBundle#137]
Hello spea,

i would appreciate if you can update this bundle to 3.1.
I would like to use the symfony LDAP functionality without loosing your bundle.

Best regards

DjWindless

**Comment by Spea** [comment]
The bundle allows version `~3.0` which means you can use 3.1 too, so I'm not sure whats the exact issue here.

**Comment by DJWindless** [comment]
Big sorry, was my false. You can delete this issue.
