### ISSUE TITLE
"Dependency cache keys not yet generated"

### ISSUE THREAD

**Issue by luebbert42** [Spea/SpBowerBundle#67]
When I run php app/console assetic:dump in Symfony 2.3.7 I am getting the following error message:

[Sp\BowerBundle\Bower\Exception\RuntimeException]
  Dependency cache keys not yet generated, run "app/console sp:bower:install" to initiate the cache: Cached dependencies for "/Users/luebbert/tmp/Symfony/app/cache/dev/sp_bower" not found, c
  reate it with the method createDependencyMappingCache().

I did the following to reproduce the problem with a fresh Symfony 2.3.7 project:
- php composer.phar create-project symfony/framework-standard-edition demo 2.3.*
- php app/console generate:bundle
- created AcmeFooBundle
-  followed the install documentation for the spPowerBundle (did not do step 7, as it seems to be optional)

I can upload the demo project if this helps. This issue is not urgent, was mainly playing around with the bundle :-)

**Comment by ProjectPwnable** [comment]
Since this is still present, here's the solution for anyone else on Windows:

1. The problem lies in Doctrine\Common\Cache\FileCache::getFilename() (specifically, the second argument of str_split)
2. Override the getFilename() of Doctrine\Common\Cache\FileCache with the class at the bottom
3. Add the following parameter to your parameters.yml:

```yml
sp_bower.filesystem_cache.class: YourBundle\BowerBridge\WindowsFilesystemCache
```

**New class**
```php
use Doctrine\Common\Cache\FilesystemCache;

class WindowsFilesystemCache extends FilesystemCache
{
    /**
     * FilesystemCache marks this as private... so we must override
     * @var string[] regular expressions for replacing disallowed characters in file name
     */
    private $disallowedCharacterPatterns = array(
        '/\-/', // replaced to disambiguate original `-` and `-` derived from replacements
        '/[^a-zA-Z0-9\-_\[\]]/' // also excludes non-ascii chars (not supported, depending on FS)
    );

    /**
     * FilesystemCache marks this as private... so we must override
     * @var string[] replacements for disallowed file characters
     */
    private $replacementCharacters = array('__', '-');


    /**
     * @param string $id
     *
     * @return string
     */
    protected function getFilename($id)
    {
        return $this->directory
        . DIRECTORY_SEPARATOR
        . implode(str_split(hash('sha256', $id), 16), DIRECTORY_SEPARATOR)
        . DIRECTORY_SEPARATOR
        . preg_replace($this->disallowedCharacterPatterns, $this->replacementCharacters, $id)
        . $this->getExtension();
    }
}
```

Note: you have to copy/paste the disallowedCharacterPatterns and replacementCharacters from the parent class, since they are marked private and have no accessors.

**Comment by gesof** [comment]
run "composer install" again to refresh the cache
