### ISSUE TITLE
Unexpected token "text" of value " <script src="" ("end of statement block" expected)

### ISSUE THREAD

**Issue by daFish** [Spea/SpBowerBundle#88]
Hi there.

I'm using version 0.10 of this bundle and have the following problem which only occurs with a fresh cache after it was cleaned by hand or during a run of `composer update`.

> Unexpected token "text" of value " <script src="" ("end of statement block" expected) in ::full-layout.html.twig at line 81

As the error message is a bit misleading I thought the issue came from FriendsOfSymfony/FOSJsRoutingBundle#146 which isn't the case. I tracked it down to this bundle when the assetic tags are used, e.g. `@jquery_js`.

``` php
{% javascripts
    '@jquery_js'
    '@select2_js'
%}
```

If I remove them and clear the cache, the error is gone so I guess this bundle affects it. Anything that I can do?

**Comment by stripyshirtguy** [comment]
Could be related to https://github.com/symfony/assetic-bundle/issues/29 / https://github.com/twigphp/Twig/pull/610
